export const ERROR_MESSAGES = {
    // Firebase Authentication Errors
    'auth/user-not-found': 'No account found with this email address.',
    'auth/wrong-password': 'Incorrect password.',
    'auth/invalid-email': 'Invalid email address.',
    'auth/too-many-requests': 'Too many failed login attempts. Please try again later or use Google login.',
    'auth/user-disabled': 'This account has been disabled.',
    'auth/operation-not-allowed': 'This operation is not allowed.',
    'auth/weak-password': 'Password should be at least 6 characters.',
    'auth/email-already-in-use': 'An account with this email already exists.',
    'auth/invalid-credential': 'Invalid credentials. Please check your email and password.',
    'auth/account-exists-with-different-credential': 'An account already exists with the same email address but different sign-in credentials.',
    'auth/requires-recent-login': 'This operation requires recent authentication. Please log in again.',
    'auth/network-request-failed': 'Network error. Please check your internet connection.',
    'auth/popup-closed-by-user': 'Login popup was closed before completing authentication.',
    'auth/cancelled-popup-request': 'Only one popup request is allowed at a time.',
    'auth/popup-blocked': 'Login popup was blocked by the browser. Please allow popups for this site.',
    'auth/unauthorized-domain': 'This domain is not authorized for OAuth operations.',
    'auth/invalid-api-key': 'Invalid API key.',
    'auth/app-not-authorized': 'This app is not authorized to use Firebase Authentication.',
    'auth/expired-action-code': 'The action code has expired.',
    'auth/invalid-action-code': 'The action code is invalid.',
    'auth/missing-action-code': 'Action code is required.',
    'auth/quota-exceeded': 'Quota exceeded. Please try again later.',
    'auth/retry-popup-request': 'Please retry the popup request.',
    'auth/invalid-verification-code': 'Invalid verification code.',
    'auth/invalid-verification-id': 'Invalid verification ID.',
    'auth/missing-verification-code': 'Verification code is required.',
    'auth/missing-verification-id': 'Verification ID is required.',
    'auth/credential-already-in-use': 'This credential is already associated with a different user account.',
    'auth/phone-number-already-exists': 'This phone number is already in use.',
    'auth/project-not-found': 'Firebase project not found.',
    'auth/insufficient-permission': 'Insufficient permissions to perform this operation.',
    'auth/argument-error': 'Invalid argument provided.',
    'auth/invalid-app-credential': 'Invalid app credential.',
    'auth/invalid-app-instance-id': 'Invalid app instance ID.',
    'auth/invalid-user-token': 'Invalid user token.',
    'auth/invalid-tenant-id': 'Invalid tenant ID.',
    'auth/unsupported-tenant-operation': 'This operation is not supported for this tenant.',
    'auth/tenant-id-mismatch': 'Tenant ID mismatch.',
    'auth/operation-not-supported-in-this-environment': 'This operation is not supported in this environment.',
    'auth/unsupported-persistence-type': 'Unsupported persistence type.',
    'auth/invalid-persistence-type': 'Invalid persistence type.',
    'auth/invalid-credential-type': 'Invalid credential type.',
    'auth/invalid-provider-id': 'Invalid provider ID.',
    'auth/invalid-oauth-provider': 'Invalid OAuth provider.',
    'auth/invalid-oauth-client-id': 'Invalid OAuth client ID.',
    'auth/invalid-cert-hash': 'Invalid certificate hash.',
    'auth/invalid-verification-email': 'Invalid verification email.',
    'auth/invalid-recaptcha-token': 'Invalid reCAPTCHA token.',
    'auth/invalid-recaptcha-action': 'Invalid reCAPTCHA action.',
    'auth/missing-recaptcha-token': 'reCAPTCHA token is required.',
    'auth/missing-recaptcha-action': 'reCAPTCHA action is required.',
    'auth/invalid-recaptcha-score': 'Invalid reCAPTCHA score.',
    'auth/invalid-recaptcha-secret': 'Invalid reCAPTCHA secret.',
    'auth/invalid-recaptcha-response': 'Invalid reCAPTCHA response.',
    'auth/invalid-recaptcha-site-key': 'Invalid reCAPTCHA site key.',
    'auth/invalid-recaptcha-version': 'Invalid reCAPTCHA version.',
    'auth/invalid-recaptcha-action-name': 'Invalid reCAPTCHA action name.',
    'auth/invalid-recaptcha-action-score': 'Invalid reCAPTCHA action score.',
    'auth/invalid-recaptcha-action-timeout': 'Invalid reCAPTCHA action timeout.',
    'auth/invalid-recaptcha-action-hostname': 'Invalid reCAPTCHA action hostname.',
    'auth/invalid-recaptcha-action-apk-package-name': 'Invalid reCAPTCHA action APK package name.',
    'auth/invalid-recaptcha-action-app-version': 'Invalid reCAPTCHA action app version.',
    'auth/invalid-recaptcha-action-device-family': 'Invalid reCAPTCHA action device family.',
    'auth/invalid-recaptcha-action-platform': 'Invalid reCAPTCHA action platform.',
    'auth/invalid-recaptcha-action-app-id': 'Invalid reCAPTCHA action app ID.',
    'auth/invalid-recaptcha-action-install-id': 'Invalid reCAPTCHA action install ID.',
    'auth/invalid-recaptcha-action-device-model': 'Invalid reCAPTCHA action device model.',
    'auth/invalid-recaptcha-action-device-brand': 'Invalid reCAPTCHA action device brand.',
    'auth/invalid-recaptcha-action-device-os': 'Invalid reCAPTCHA action device OS.',
    'auth/invalid-recaptcha-action-device-os-version': 'Invalid reCAPTCHA action device OS version.',
    'auth/invalid-recaptcha-action-device-locale': 'Invalid reCAPTCHA action device locale.',
    'auth/invalid-recaptcha-action-device-timezone': 'Invalid reCAPTCHA action device timezone.',
    'auth/invalid-recaptcha-action-device-screen-resolution': 'Invalid reCAPTCHA action device screen resolution.',
    'auth/invalid-recaptcha-action-device-screen-density': 'Invalid reCAPTCHA action device screen density.',
    'auth/invalid-recaptcha-action-device-screen-rotation': 'Invalid reCAPTCHA action device screen rotation.',
    'auth/invalid-recaptcha-action-device-screen-orientation': 'Invalid reCAPTCHA action device screen orientation.',
    'auth/invalid-recaptcha-action-device-screen-color-depth': 'Invalid reCAPTCHA action device screen color depth.',
    'auth/invalid-recaptcha-action-device-screen-pixel-ratio': 'Invalid reCAPTCHA action device screen pixel ratio.',
    'auth/invalid-recaptcha-action-device-screen-available-width': 'Invalid reCAPTCHA action device screen available width.',
    'auth/invalid-recaptcha-action-device-screen-available-height': 'Invalid reCAPTCHA action device screen available height.',
    'auth/invalid-recaptcha-action-device-screen-width': 'Invalid reCAPTCHA action device screen width.',
    'auth/invalid-recaptcha-action-device-screen-height': 'Invalid reCAPTCHA action device screen height.',
    'auth/invalid-recaptcha-action-device-screen-avail-width': 'Invalid reCAPTCHA action device screen available width.',
    'auth/invalid-recaptcha-action-device-screen-avail-height': 'Invalid reCAPTCHA action device screen available height.',
}